# Generated by Django 5.2.7 on 2025-10-24 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(help_text='Titre du souvenir', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée du souvenir')),
                ('date_evenement', models.DateField(help_text="Date de l'événement")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='souvenirs/photos/%Y/%m/')),
                ('video', models.FileField(blank=True, null=True, upload_to='souvenirs/videos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souvenirs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Souvenir',
                'verbose_name_plural': 'Souvenirs',
                'ordering': ['-date_evenement'],
            },
        ),
    ]
