# Generated by Django 5.2.7 on 2025-10-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souvenir',
            name='emotion',
            field=models.CharField(choices=[('joy', 'Joy'), ('sadness', 'Sadness'), ('nostalgia', 'Nostalgia'), ('gratitude', 'Gratitude'), ('excitement', 'Excitement'), ('peace', 'Peace'), ('love', 'Love'), ('surprise', 'Surprise'), ('pride', 'Pride'), ('neutral', 'Neutral')], default='neutral', help_text='Primary emotion', max_length=50),
        ),
    ]
