# Generated by Django 5.2.7 on 2025-10-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_souvenir_emotion'),
    ]

    operations = [
    ]
