# Generated by Django 5.2.7 on 2025-10-24 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_souvenir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('consistency', 'Constance'), ('reflective', 'Reflexif'), ('emotional_balance', 'Equilibre Emotionnel'), ('memory_keeper', 'Gardien de Memoires'), ('storyteller', 'Conteur'), ('explorer', 'Explorateur')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='trophy', max_length=10)),
                ('requirement_value', models.IntegerField(help_text='Valeur requise pour debloquer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='souvenir',
            name='emotion',
            field=models.CharField(choices=[('joy', '😊 Joie'), ('love', '❤️ Amour'), ('sadness', '😢 Tristesse'), ('anger', '😠 Colère'), ('fear', '😰 Peur'), ('surprise', '😲 Surprise'), ('nostalgia', '🌅 Nostalgie'), ('pride', '🏆 Fierté'), ('gratitude', '🙏 Gratitude'), ('neutral', '😐 Neutre')], default='neutral', help_text='Émotion associée', max_length=20),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Rendre ce souvenir visible publiquement'),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='note_associee',
            field=models.ForeignKey(blank=True, help_text='Note du journal associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='souvenirs', to='core.note'),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='theme',
            field=models.CharField(choices=[('family', '👨\u200d👩\u200d👧 Famille'), ('friends', '👫 Amis'), ('travel', '✈️ Voyage'), ('work', '💼 Travail'), ('education', '🎓 Éducation'), ('celebration', '🎉 Célébration'), ('achievement', '🏅 Réussite'), ('nature', '🌳 Nature'), ('sports', '⚽ Sport'), ('arts', '🎨 Arts & Culture'), ('other', '📌 Autre')], default='other', help_text='Thème du souvenir', max_length=20),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0, help_text='Progression actuelle vers le badge')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
