# Generated by Django 5.2.7 on 2025-10-25 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_souvenir_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeHumeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensite', models.IntegerField(choices=[(1, 'Très faible'), (2, 'Faible'), (3, 'Modérée'), (4, 'Forte'), (5, 'Très forte')], default=3, help_text="Intensité de l'humeur (1-5)")),
                ('note', models.TextField(blank=True, default='', help_text='Note sur cette humeur')),
                ('date_association', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrée-Humeur',
                'verbose_name_plural': 'Entrées-Humeurs',
                'ordering': ['-intensite', '-date_association'],
            },
        ),
        migrations.CreateModel(
            name='EntreeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_association', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrée-Tag',
                'verbose_name_plural': 'Entrées-Tags',
                'ordering': ['-date_association'],
            },
        ),
        migrations.CreateModel(
            name='Humeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'humeur", max_length=50, unique=True)),
                ('emoji', models.CharField(default='😊', help_text="Emoji représentant l'humeur", max_length=10)),
                ('couleur', models.CharField(default='#FFD700', help_text='Couleur associée (hex)', max_length=7)),
                ('description', models.TextField(blank=True, default='', help_text="Description de l'humeur")),
            ],
            options={
                'verbose_name': 'Humeur',
                'verbose_name_plural': 'Humeurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du tag', max_length=50, unique=True)),
                ('couleur', models.CharField(default='#3498db', help_text='Couleur du tag (hex)', max_length=7)),
                ('description', models.TextField(blank=True, default='', help_text='Description du tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='entreejournal',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Entrée favorite'),
        ),
        migrations.AddField(
            model_name='entreejournal',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Entrée publique'),
        ),
        migrations.AddField(
            model_name='entreejournal',
            name='lieu',
            field=models.CharField(blank=True, default='', help_text="Lieu où l'entrée a été écrite", max_length=200),
        ),
        migrations.AddField(
            model_name='entreejournal',
            name='meteo',
            field=models.CharField(blank=True, default='', help_text='Météo du jour', max_length=50),
        ),
        migrations.AlterField(
            model_name='entreejournal',
            name='contenu_texte',
            field=models.TextField(help_text="Contenu de l'entrée"),
        ),
        migrations.AlterField(
            model_name='entreejournal',
            name='titre',
            field=models.CharField(help_text="Titre de l'entrée", max_length=200),
        ),
        migrations.AddIndex(
            model_name='entreejournal',
            index=models.Index(fields=['-date_creation'], name='core_entree_date_cr_a38187_idx'),
        ),
        migrations.AddIndex(
            model_name='entreejournal',
            index=models.Index(fields=['utilisateur', '-date_creation'], name='core_entree_utilisa_227063_idx'),
        ),
        migrations.AddField(
            model_name='entreehumeur',
            name='entree_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entree_humeurs', to='core.entreejournal'),
        ),
        migrations.AddField(
            model_name='entreetag',
            name='entree_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entree_tags', to='core.entreejournal'),
        ),
        migrations.AddField(
            model_name='entreehumeur',
            name='humeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entree_humeurs', to='core.humeur'),
        ),
        migrations.AddField(
            model_name='tag',
            name='utilisateur',
            field=models.ForeignKey(blank=True, help_text='Propriétaire du tag (null = tag global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entreetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entree_tags', to='core.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='entreehumeur',
            unique_together={('entree_journal', 'humeur')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('nom', 'utilisateur')},
        ),
        migrations.AlterUniqueTogether(
            name='entreetag',
            unique_together={('entree_journal', 'tag')},
        ),
    ]
