# Generated by Django 5.2.7 on 2025-10-25 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_souvenir_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoireInspirante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reflexion_text', models.TextField(help_text="Texte de réflexion personnel de l'utilisateur")),
                ('histoire_generee', models.TextField(help_text='Histoire inspirante générée')),
                ('celebrite', models.CharField(help_text="Nom de la célébrité mentionnée dans l'histoire", max_length=200)),
                ('est_simulee', models.BooleanField(default=True, help_text='True si histoire simulée, False si générée par IA')),
                ('modele_utilise', models.CharField(blank=True, default='', help_text='Modèle IA utilisé (ex: gpt-4o-mini)', max_length=100)),
                ('is_favorite', models.BooleanField(default=False, help_text='Marquée comme favorite')),
                ('notes_personnelles', models.TextField(blank=True, default='', help_text="Notes personnelles de l'utilisateur sur cette histoire")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histoires_inspirantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histoire Inspirante',
                'verbose_name_plural': 'Histoires Inspirantes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utilisateur', '-created_at'], name='core_histoi_utilisa_123606_idx'), models.Index(fields=['is_favorite'], name='core_histoi_is_favo_437413_idx')],
            },
        ),
    ]
