# Generated by Django 5.2.7 on 2025-10-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entreehumeur_entreetag_humeur_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreejournal',
            name='auto_summary',
            field=models.TextField(blank=True, default='', help_text="Résumé automatique généré par l'IA"),
        ),
    ]
