# Generated by Django 5.2.7 on 2025-10-24 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_badge_souvenir_emotion_souvenir_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souvenir',
            name='note_associee',
        ),
        migrations.AddField(
            model_name='souvenir',
            name='ai_emotion_detected',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='Résumé automatique généré par IA', null=True),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags générés par IA'),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Marqué comme favori'),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='lieu',
            field=models.CharField(blank=True, help_text="Lieu de l'événement", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='personnes_presentes',
            field=models.TextField(blank=True, help_text='Personnes présentes', null=True),
        ),
        migrations.AlterField(
            model_name='souvenir',
            name='emotion',
            field=models.CharField(blank=True, choices=[('joie', '😊 Joie'), ('tristesse', '😢 Tristesse'), ('nostalgie', '🌅 Nostalgie'), ('surprise', '😮 Surprise'), ('amour', '❤️ Amour'), ('colere', '😠 Colère'), ('peur', '😨 Peur'), ('neutre', '😐 Neutre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='souvenir',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Visible par tous'),
        ),
        migrations.AlterField(
            model_name='souvenir',
            name='theme',
            field=models.CharField(blank=True, choices=[('famille', '👨\u200d👩\u200d👧\u200d👦 Famille'), ('amis', '👫 Amis'), ('voyage', '✈️ Voyage'), ('travail', '💼 Travail'), ('education', '🎓 Éducation'), ('amour', '💕 Amour'), ('hobby', '🎨 Hobby'), ('sport', '⚽ Sport'), ('celebration', '🎉 Célébration'), ('autre', '📌 Autre')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EntreeJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('contenu_texte', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_journal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée de Journal',
                'verbose_name_plural': 'Entrées de Journal',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ExportPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_export', models.DateTimeField(auto_now_add=True)),
                ('chemin_fichier', models.FileField(blank=True, null=True, upload_to='exports/pdf/%Y/%m/')),
                ('titre_export', models.CharField(default='Mon Journal de Souvenirs', max_length=200)),
                ('date_debut', models.DateField(blank=True, help_text='Filtre: date de début', null=True)),
                ('date_fin', models.DateField(blank=True, help_text='Filtre: date de fin', null=True)),
                ('souvenirs_inclus', models.JSONField(blank=True, default=list, help_text='Liste des IDs des souvenirs inclus')),
                ('status', models.CharField(choices=[('en_cours', '⏳ En cours'), ('termine', '✅ Terminé'), ('erreur', '❌ Erreur')], default='en_cours', max_length=20)),
                ('taille_fichier', models.IntegerField(blank=True, help_text='Taille en octets', null=True)),
                ('nombre_pages', models.IntegerField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports_pdf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export PDF',
                'verbose_name_plural': 'Exports PDF',
                'ordering': ['-date_export'],
            },
        ),
        migrations.CreateModel(
            name='PartageSouvenir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_visibilite', models.CharField(choices=[('prive', '🔒 Privé'), ('amis', '👥 Amis'), ('public', '🌍 Public')], default='prive', max_length=20)),
                ('date_partage', models.DateTimeField(auto_now_add=True)),
                ('message_partage', models.TextField(blank=True, help_text='Message accompagnant le partage', null=True)),
                ('vues_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('souvenir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='core.souvenir')),
            ],
            options={
                'verbose_name': 'Partage de Souvenir',
                'verbose_name_plural': 'Partages de Souvenirs',
                'ordering': ['-date_partage'],
            },
        ),
        migrations.CreateModel(
            name='SuiviMotivationnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nb_souvenirs_ajoutes', models.IntegerField(default=0)),
                ('nb_entrees_journal', models.IntegerField(default=0)),
                ('dernier_souvenir_ajoute', models.DateTimeField(blank=True, null=True)),
                ('derniere_entree_journal', models.DateTimeField(blank=True, null=True)),
                ('jours_consecutifs', models.IntegerField(default=0, help_text="Nombre de jours consécutifs d'écriture")),
                ('meilleure_serie', models.IntegerField(default=0, help_text='Meilleure série de jours consécutifs')),
                ('derniere_activite', models.DateField(blank=True, null=True)),
                ('total_mots_ecrits', models.IntegerField(default=0)),
                ('souvenirs_partages', models.IntegerField(default=0)),
                ('exports_realises', models.IntegerField(default=0)),
                ('messages_motivationnels', models.JSONField(blank=True, default=list)),
                ('niveau_motivation', models.CharField(choices=[('debutant', '🌱 Débutant'), ('regulier', '⭐ Régulier'), ('assidu', '🔥 Assidu'), ('expert', '🏆 Expert'), ('maitre', '👑 Maître')], default='debutant', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_motivationnel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi Motivationnel',
                'verbose_name_plural': 'Suivis Motivationnels',
            },
        ),
        migrations.CreateModel(
            name='SouvenirEntree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_association', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text="Note sur le lien entre le souvenir et l'entrée", null=True)),
                ('entree_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souvenirs_lies', to='core.entreejournal')),
                ('souvenir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_liees', to='core.souvenir')),
            ],
            options={
                'verbose_name': 'Association Souvenir-Entrée',
                'verbose_name_plural': 'Associations Souvenir-Entrée',
                'unique_together': {('souvenir', 'entree_journal')},
            },
        ),
    ]
