# Generated by Django 5.2.7 on 2025-10-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20251025_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='souvenir',
            name='tags_personnalises',
            field=models.JSONField(blank=True, default=list, help_text='User-defined custom tags'),
        ),
    ]
