# Generated by Django 5.2.7 on 2025-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entreejournal_auto_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nom',
            field=models.CharField(help_text='Nom du tag', max_length=50),
        ),
    ]
