# Generated by Django 5.2.7 on 2025-10-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_histoireinspirante'),
        ('core', '0004_add_tags_personnalises'),
    ]

    operations = [
    ]
