# Generated by Django 5.2.7 on 2025-10-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20251025_2219'),
        ('core', '0005_remove_tag_unique_constraint'),
    ]

    operations = [
    ]
