# Generated by Django 5.2.7 on 2025-10-26 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20251026_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='code',
            field=models.CharField(choices=[('consistency', 'Consistency'), ('reflective', 'Reflective'), ('emotional_balance', 'Emotional Balance'), ('memory_keeper', 'Memory Keeper'), ('storyteller', 'Storyteller'), ('explorer', 'Explorer')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='requirement_value',
            field=models.IntegerField(help_text='Value required to unlock'),
        ),
        migrations.AlterField(
            model_name='entreehumeur',
            name='intensite',
            field=models.IntegerField(choices=[(1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very high')], default=3, help_text='Mood intensity (1-5)'),
        ),
        migrations.AlterField(
            model_name='entreehumeur',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Note on this mood'),
        ),
        migrations.AlterField(
            model_name='entreejournal',
            name='auto_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated summary'),
        ),
        migrations.AlterField(
            model_name='entreejournal',
            name='contenu_texte',
            field=models.TextField(help_text='Entry content'),
        ),
        migrations.AlterField(
            model_name='entreejournal',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Favorite entry'),
        ),
        migrations.AlterField(
            model_name='entreejournal',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public entry'),
        ),
        migrations.AlterField(
            model_name='entreejournal',
            name='lieu',
            field=models.CharField(blank=True, default='', help_text='Location where the entry was written', max_length=200),
        ),
        migrations.AlterField(
            model_name='entreejournal',
            name='meteo',
            field=models.CharField(blank=True, default='', help_text='Weather on the day', max_length=50),
        ),
        migrations.AlterField(
            model_name='entreejournal',
            name='titre',
            field=models.CharField(help_text='Entry title', max_length=200),
        ),
        migrations.AlterField(
            model_name='humeur',
            name='couleur',
            field=models.CharField(default='#FFD700', help_text='Associated color (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='humeur',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Mood description'),
        ),
        migrations.AlterField(
            model_name='humeur',
            name='emoji',
            field=models.CharField(default='😊', help_text='Emoji representing the mood', max_length=10),
        ),
        migrations.AlterField(
            model_name='humeur',
            name='nom',
            field=models.CharField(help_text='Mood name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='couleur',
            field=models.CharField(default='#3498db', help_text='Tag color (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Tag description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nom',
            field=models.CharField(help_text='Tag name', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='utilisateur',
            field=models.ForeignKey(blank=True, help_text='Tag owner (null = global tag)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
