# Generated by Django 5.2.6 on 2025-10-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20251026_1347'),
        ('core', '0006_moodanalysis_moodrecommendation'),
    ]

    operations = [
    ]
