# Generated by Django 5.2.7 on 2025-10-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_badge_code_alter_badge_requirement_value_and_more'),
        ('core', '0008_alter_badge_code_alter_badge_requirement_value_and_more'),
    ]

    operations = [
    ]
