# Generated by Django 5.2.7 on 2025-10-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20251026_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='histoireinspirante',
            name='challenge_description',
            field=models.TextField(blank=True, default='', help_text='Description du défi concret à réaliser'),
        ),
        migrations.AddField(
            model_name='histoireinspirante',
            name='challenge_title',
            field=models.CharField(blank=True, default='', help_text='Titre du défi quotidien', max_length=300),
        ),
        migrations.AddField(
            model_name='histoireinspirante',
            name='emotion_detected',
            field=models.CharField(blank=True, default='', help_text='Émotion principale détectée', max_length=100),
        ),
        migrations.AddField(
            model_name='histoireinspirante',
            name='motivation_quote',
            field=models.TextField(blank=True, default='', help_text='Citation motivante'),
        ),
        migrations.AddField(
            model_name='histoireinspirante',
            name='story_content',
            field=models.TextField(blank=True, default='', help_text="Contenu de l'histoire inspirante"),
        ),
        migrations.AddField(
            model_name='histoireinspirante',
            name='story_title',
            field=models.CharField(blank=True, default='', help_text="Titre de l'histoire (ex: L'histoire de J.K. Rowling)", max_length=300),
        ),
    ]
