# Generated by Django 5.2.7 on 2025-10-26 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_histoireinspirante_challenge_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheQuotidienne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(help_text='Titre de la tâche', max_length=300)),
                ('description', models.TextField(help_text='Description détaillée de la tâche')),
                ('date_assignee', models.DateField(help_text='Date pour laquelle la tâche est assignée')),
                ('heure_rappel', models.TimeField(blank=True, help_text='Heure de rappel optionnelle', null=True)),
                ('statut', models.CharField(choices=[('pending', 'À faire'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('skipped', 'Passée')], default='pending', max_length=20)),
                ('date_completion', models.DateTimeField(blank=True, help_text='Date de complétion', null=True)),
                ('notes_utilisateur', models.TextField(blank=True, default='', help_text='Notes personnelles sur la tâche')),
                ('generee_par_ia', models.BooleanField(default=False, help_text='True si générée par IA')),
                ('categorie', models.CharField(blank=True, default='', help_text='Catégorie de la tâche (ex: bien-être, développement personnel)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('histoire_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_generees', to='core.histoireinspirante')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_quotidiennes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche Quotidienne',
                'verbose_name_plural': 'Tâches Quotidiennes',
                'ordering': ['date_assignee', '-created_at'],
                'indexes': [models.Index(fields=['utilisateur', 'date_assignee'], name='core_tacheq_utilisa_423b10_idx'), models.Index(fields=['statut'], name='core_tacheq_statut_6db7dd_idx'), models.Index(fields=['-created_at'], name='core_tacheq_created_d11b52_idx')],
            },
        ),
    ]
