# Generated by Django 5.2.7 on 2025-10-26 22:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tachequotidienne'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefiQuotidien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(help_text='Titre du défi (ex: Médite 10 minutes)', max_length=300)),
                ('description', models.TextField(help_text='Description détaillée du défi')),
                ('categorie', models.CharField(blank=True, default='', help_text='Catégorie (ex: bien-être, productivité, social)', max_length=100)),
                ('date_defi', models.DateField(help_text='Date prévue pour ce défi')),
                ('duree_estimee', models.IntegerField(default=15, help_text='Durée estimée en minutes')),
                ('priorite', models.IntegerField(default=1, help_text='Priorité (1=haute, 2=moyenne, 3=basse)')),
                ('statut', models.CharField(choices=[('pending', 'À faire'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('skipped', 'Ignoré')], default='pending', max_length=20)),
                ('date_completion', models.DateTimeField(blank=True, help_text='Date de complétion', null=True)),
                ('notes_utilisateur', models.TextField(blank=True, default='', help_text="Notes de l'utilisateur après complétion")),
                ('est_genere_par_ia', models.BooleanField(default=True, help_text='True si généré par IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('histoire_inspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defis', to='core.histoireinspirante')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defis_quotidiens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Défi Quotidien',
                'verbose_name_plural': 'Défis Quotidiens',
                'ordering': ['date_defi', 'priorite'],
            },
        ),
        migrations.DeleteModel(
            name='TacheQuotidienne',
        ),
        migrations.AddIndex(
            model_name='defiquotidien',
            index=models.Index(fields=['utilisateur', 'date_defi'], name='core_defiqu_utilisa_c80b04_idx'),
        ),
        migrations.AddIndex(
            model_name='defiquotidien',
            index=models.Index(fields=['statut'], name='core_defiqu_statut_b07574_idx'),
        ),
    ]
